config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/users/search" => "users#search", constraints: { format: "json" }
  get "/profile" => "users#show"
  get "/profile/:username" => "users#show"

  get "/contact" => "application#contact"
  get "/about" => "application#about"

  resources :cubes
  get "/draft/:id" => "cubes#draft"

  resources :decks, only: %i[show edit]

  resources :follows, only: %i[index show create destroy]

  root to: "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_one :mtg_card, class_name: "MTG::Card", dependent: :destroy

  acts_as_taggable
end

app/models/cube.rb
class Cube < ApplicationRecord
  has_many :cards, dependent: :destroy
  has_many :decks, dependent: :destroy

  acts_as_taggable_on :cube_tags
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :cube
  has_many :cards, dependent: :destroy
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :source, class_name: "User", inverse_of: :follows
  belongs_to :destination, class_name: "User", inverse_of: false

  delegate :username, to: :destination
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  # :omniauthable

  attr_writer :login

  has_many :cubes, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :decks, through: :cube, dependent: :destroy
  has_many :follows, dependent: :destroy, inverse_of: :source, foreign_key: :source_id
  has_many :followings, through: :follows, source: :destination

  acts_as_taggable_on :used_tags

  validates :username,
            presence: true,
            uniqueness: { message: "taken" },
            format: {
              with: /\A[a-z0-9_.-]{8,24}\z/i,
              message: "can only use letters, numbers, and the symbols . - and _"
            },
            length: { in: 8..24, message: "must be between 8 and 24 characters" }

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  validates :password,
            format: {
              with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[\x20-\x7E]{8,24}\z/,
              message: "requires a lowercase letter, an uppercase letter, one digit, and a special character"
            },
            length: { in: 8..24, message: "must be between 8 and 24 characters" }

  def self.search(query, limit = 10, current_user = nil)
    users = if query != ""
              User.where("username like :search OR email like :search", search: "%#{query}%")
            else
              User.order(:username)
            end

    users = users.reject { |user| user.id == current_user.id } if current_user

    return users[0..limit-1] if users.count > limit.to_i
    users
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    conditions[:email].downcase! if conditions[:email]
    if conditions.key?(:login)
      find_by(["username = :value OR lower(email) = lower(:value)", { value: conditions[:login] }])
    elsif conditions.key?(:username) || conditions.key?(:email)
      find_by(conditions.to_h)
    end
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery

  before_action :http_basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @current_user = !current_user.nil?
  end

  def contact; end

  def about; end

  private

  def http_basic_auth
    return unless ENV["HTTP_BASIC_AUTH_ENABLED"] == "true"

    authenticate_or_request_with_http_basic("Username and Password please") do |username, password|
      username == ENV["HTTP_BASIC_AUTH_USERNAME"] && password == ENV["HTTP_BASIC_AUTH_PASSWORD"]
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :remember_me)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:login, :username, :email, :password, :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/cubes_controller.rb
class CubesController < ApplicationController
  def index
    set_cubes
  end

  def show
    set_cube
  end

  def new
    @cube = Cube.new
  end

  def create
    cube = Cube.new(cube_params)

    return redirect_to cubes_url, notice: "Cube successfully created." if cube.save
    render :new
  end

  def edit
    set_cube
  end

  def update
    set_cube
    return redirect_to @cube, notice: "Cube successfully updated." if @cube.update(cube_params)
    render :edit
  end

  def destroy
    set_cube
    @cube.destroy
    redirect_to cubes_url, notice: "Cube successfully deleted."
  end

  def draft
    set_cube
  end

  private

  def set_cubes
    @cubes = Cube.all
  end

  def set_cube
    @cube = current_user.cubes.find(params[:id])
  end

  def cube_params
    params.require(:cube).permit(:name, :category)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @follows = []
    @follows = Follow.where(source_id: current_user.id) if current_user
  end

  def show
    set_follow

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @follow.to_json }
    end
  end

  def create
    return unless valid_follow?
    follow = Follow.new(source_id: current_user.id, destination_id: params[:destination_id])
    return follow if follow.save
  end

  def destroy
    set_follow
    unfollowed_username = @follow.username
    @follow.destroy
    redirect_to "/profile", notice: "#{unfollowed_username} unfollowed."
  end

  private

  def set_follow
    return unless current_user
    @follow = (
      if params[:destination_id]
        current_user.follows.where(destination_id: params[:destination_id])
      else
        current_user.follows.find(params[:id])
      end
    )
    authorize @follow
  end

  def follow_params
    params.require(:follow).permit(:id, :destination_id)
  end

  def valid_follow?
    return false if current_user.nil?
    return false if current_user.to_param == params[:destination_id]
    return false if follow_exists?(current_user.id, params[:destination_id])
    true
  end

  def follow_exists?(source_id, destination_id)
    Follow.where(source_id: source_id, destination_id: destination_id).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    render json: User.search(params[:search] || "", params[:limit] || 10, current_user || nil)
  end

  def show
    set_user
    @current_user = !current_user.nil?

    return redirect_to "/", notice: "Sign in to visit your profile" if !@current_user && params[:username].nil?
    return redirect_to "/", notice: "#{@user.username} has not confirmed their account yet." if @unconfirmed_user

    authorize @user
    set_cubes
    set_decks
    set_cards
    set_follows
  end

  private

  def set_user
    @other_user = true
    @unconfirmed_user = false

    if params[:username]
      @user = User.where(username: params[:username])[0]
      @other_user = false if @user == current_user
    elsif current_user
      @user = current_user
      @other_user = false
    end

    @unconfirmed_user = true if @other_user && !@user&.confirmed?
  end

  def set_cubes
    @cubes = @user.cubes || []
  end

  def set_decks
    @decks = @cubes.any? ? @user&.decks : []
  end

  def set_cards
    @cards = @other_user ? [] : @user&.cards
  end

  def set_follows
    @follows = @other_user ? [] : @user&.follows
  end

  def user_params
    params.require(:user).permit(:id, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
Application#about

app/views/application/contact.html.erb
Application#contact

app/views/application/index.html.erb
Application#index

<%= render partial: "shared/user_search" %>

app/views/cubes/_form.html.erb
Cubes#form

app/views/cubes/draft.html.erb
Cubes#draft

app/views/cubes/edit.html.erb
Cubes#edit

app/views/cubes/index.html.erb
Cubes#index

app/views/cubes/new.html.erb
Cubes#new

app/views/cubes/show.html.erb
Cubes#show

app/views/decks/edit.html.erb
Decks#edit

app/views/decks/show.html.erb
Decks#show

app/views/follows/_index.html.erb
<% if follows&.any? %>
  <section class="user-profile__section user-profile__follows-wrap">
    <header class="user-profile__section-header">
      <h3 class="user-profile__section-heading">Follows:</h3>
    </header>
    <ul class="user-profile__follows-list">
      <% follows.each do |follow| %>
        <li class="user-profile__follow follow">
          <%= link_to follow.username, "/profile/#{follow.username}" %>
        </li>
      <% end %>
    </ul>
  </section>
<% else %>
  <div class="no-objects no-objects__user-follows">
    <span>You don't follow any users yet, </span>
    <%= link_to "find a friend", "/" %>
    <span>!</span>
  </div>
<% end %>

app/views/follows/_new.html.erb
<% if other_user && !unconfirmed_user %>
  <div class="user-profile__follow-wrap">
    <%= link_to follows_path(destination_id: user.to_param), class: "btn user-profile__follow-btn" do %>
      <span>Follow </span>
      <span class="username"><%= user.username %></span>
    <% end %>
  </div>
<% end %>

app/views/follows/show.html.erb
<li className="list__item user-search__result search-result__wrapper">
  <header className="search-result__header">
    <h4 className="search-result__header">
      <%= link_to "User: #{@follow.username}", "/profile/#{@follow.username}", class: "search-result__link" %>
    </h4>
  </header>
  <div className="search-result__info">
    <%= link_to "View profile", "/profile/#{@follow.username}", class: "search-result__button btn" %>
  </div>
</li>

app/views/layouts/_footer.html.erb
<footer class="app__footer">
  <nav class="menu__wrap footer__menu">
    <ul class="menu">
      <li class="menu__item">
        <%= link_to "About", "/about", class: "menu__link" %>
      </li>
      <li class="menu-item">
        <%= link_to "Contact", "/contact", class: "menu__link" %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="app__header">
  <h1 class="title app__title">MTG Cube Draft</h1>

  <nav class="menu__wrap header__menu">
    <ul class="menu">
      <% if user_signed_in? %>
        <li class="menu__item">
          <%= link_to "Home", "/", class: "menu__link" %>
        </li>
        <li class="menu-item">
          <%= link_to "Your profile", profile_path, class: "menu__link" %>
        </li>
        <li class="menu-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "menu__link" %>
        </li>
      <% else %>
        <li class="menu__item">
          <%= link_to "Home", "/", class: "menu__link" %>
        </li>
        <li class="menu-item">
          <%= link_to "Sign in", new_user_session_path, class: "menu__link" %>
        </li>
        <li class="menu-item">
          <%= link_to "Sign up", new_user_registration_path, class: "menu__link" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
  <title>MTG Cube Draft</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
</head>

<body>
  <%= render partial: "layouts/header" %>

  <main class="app__main">
    <% if notice %>
      <div class="alert__message notice"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert__message alert"><%= alert %></div>
    <% end %>

    <%= yield %>
  </main>

  <%= render partial: "layouts/footer" %>

  <%= javascript_pack_tag "application" %>
</body>
</html>

app/views/shared/_user_search.html.erb
<% if @current_user %>
  <div id="user_search" data-current-user="true"></div>
<% else %>
  <div id="user_search"></div>
<% end %>

<%= javascript_pack_tag "UserSearch" %>

app/views/users/show.html.erb
<header class="page__header">
  <h2 class="title page__title">
    <span>User profile: </span>
    <span class="user-profile__username username"><%= @user.username %></span>
  </h2>
  <%= render partial: "follows/new", locals: {
    user: @user,
    other_user: @other_user,
    unconfirmed_user: @unconfirmed_user
  } %>
</header>

<%= render partial: "shared/user_search" %>

<% unless @unconfirmed_user %>
  <section class="user-profile__section user-profile__cubes-wrap">
    <header class="user-profile__section-header">
      <h3 class="user-profile__section-heading">Cubes:</h3>
    </header>
    <% if @cubes.any? %>
      <ul class="user-profile__cubes-list">
        <% @cubes.each do |cube| %>
          <li class="user-profile__cube cube">
            <%= cube.id %>
          </li>
        <% end %>
      </ul>
    <% elsif @other_user %>
      <div class="no-objects no-objects__user-cubes">
        <span><%= @user.username %> doesn't have any cubes yet.</span>
      </div>
    <% else %>
      <div class="no-objects no-objects__user-cubes">
        <span>You don't have any cubes yet, </span>
        <%= link_to "make one", new_cube_path %>
        <span>!</span>
      </div>
    <% end %>
  </section>

  <section class="user-profile__section user-profile__decks-wrap">
    <header class="user-profile__section-header">
      <h3 class="user-profile__section-heading">Decks:</h3>
    </header>
    <% if @decks&.any? %>
      <ul class="user-profile__decks-list">
        <% @decks.each do |deck| %>
          <li class="user-profile__deck deck">
            <%= deck.id %>
          </li>
        <% end %>
      </ul>
    <% elsif @other_user %>
      <div class="no-objects no-objects__user-decks">
        <span><%= @user.username %> doesn't have any decks yet.</span>
      </div>
    <% else %>
      <div class="no-objects no-objects__user-decks">
        <span>You don't have any decks yet, </span>
        <%= link_to "draft a cube", cubes_path %>
        <span>!</span>
      </div>
    <% end %>
  </section>

  <% unless @other_user %>
    <% if @cards&.any? %>
      <section class="user-profile__section user-profile__cards-wrap">
        <header class="user-profile__section-header">
          <h3 class="user-profile__section-heading">Cards:</h3>
        </header>
        <ul class="user-profile__cards-list">
          <% @cards.each do |card| %>
            <li class="user-profile__card card">
              <%= card.id %>
            </li>
          <% end %>
        </ul>
      </section>
    <% end %>

    <%= render partial: "follows/index", locals: { follows: @follows } %>
  <% end %>
<% else %>
  <div class="no-objects no-objects__user">This user has not yet confirmed their profile.</div>
<% end %>